### ISSUE TITLE
Integration with MCMICRO

### ISSUE THREAD

**Issue by ArtemSokolov** [vanvalenlab/deepcell-applications#16]
Dear Mesmer team,

I have been working on incorporating Mesmer into our MCMICRO pipeline. There is a couple of things that we need to handle on our side:
* https://github.com/labsyspharm/mcmicro/issues/317
* https://github.com/labsyspharm/mcmicro/issues/318

However, I also noticed that Mesmer produces a 4-dimensional array, which crashes all of our downstream modules.
``` python
>>> import tifffile
>>> tifffile.imread( 'mesmer/mask.tif' ).shape
(1, 3138, 2509, 1)
```
In general, we have been storing probability-maps as multi-channel images (where the different channels annotate pixels with probabilities that they belong to the background or different parts of the cell) and segmentation masks as plain 2-D arrays.
``` python
>>> tifffile.imread( 'unmicst/exemplar-001_Probabilities_1.tif' ).shape
(3, 3138, 2509)
>>> tifffile.imread( 'segmentation/unmicst-exemplar-001/cell.ome.tif' ).shape
(3138, 2509)
```

I was wondering what your motivation was for storing segmentation masks in 4-D arrays and whether it would make sense to introduce a new flag that would collapse this to a more conventional 2-D representation. We can then make sure that MCMICRO uses this flag on our end. This will help standardize segmentation masks produced by various modules for downstream quantification, clustering, etc.

Please let me know your thoughts.

Best,
-Artem

**Comment by ngreenwald** [comment]
Hi Artem,
We store everything as a 4D array so that the output from different steps of our pipeline is consistent, whether we have 1 batch or many batches, 1 channel or many channels, etc. Adding in a `collapse_2D` flag would be pretty easy, however. 

Do you envision any scenario where your users would want access to both the nuclear and cell segmentations? In that case there's not an easy way to collapse the output segmentation array, since the channels dim holds the different compartments.

**Comment by willgraf** [comment]
Maybe we can add a `--squeeze` option that will squeeze out any single dimension axes? This would return a 2D array in the case of a single compartment (nuclear or whole-cel) and a 3D array in the case that both segmentations are returned.

**Comment by ngreenwald** [comment]
Sure. Artem, would that work for you?

**Comment by ArtemSokolov** [comment]
Thanks, @ngreenwald and @willgraf. Having a `--squeeze` flag sounds perfect.

How do you distinguish which channel would contain nuclear vs. cellular mask? Our approach has been to output them into separate files (`cell.ome.tif` and `nuclei.ome.tif`) and then pass both files to downstream quantification, but I'm curious to learn how other groups are doing it.

**Comment by ngreenwald** [comment]
We default to not using the nuclear mask, so the pipeline assumes there is just a cell mask for signal extraction. The user can specify a flag for nuclear compartment segmentation as well, which then kicks off some post-processing to handle the different channels.

**Comment by ArtemSokolov** [comment]
Hi @willgraf and @ngreenwald 

Thanks for all your help! I got an integration prototype working. Here is a reproducible example:

``` bash
# Install Nextflow and pull the latest version of the pipeline
curl -s https://get.nextflow.io | bash
nextflow pull labsyspharm/mcmicro

# Download exemplar data
nextflow run labsyspharm/mcmicro/exemplar.nf --name exemplar-001 --path .

# Run multiple segmentation methods on the exemplar
nextflow run labsyspharm/mcmicro --in ./exemplar-001 --probability-maps unmicst,ilastik,mesmer
```

The above run takes a little over 5min on my machine. After it finishes, you can find segmentation masks in `exemplar-001/segmentation/` and spatial feature tables in `exemplar-001/quantification/`:

```
exemplar-001/segmentation/
├── ilastik-exemplar-001
│   ├── cell.ome.tif
│   └── nuclei.ome.tif
├── mesmer-exemplar-001
│   └── cell.tif
└── unmicst-exemplar-001
    ├── cell.ome.tif
    └── nuclei.ome.tif

exemplar-001/quantification/
├── ilastik-exemplar-001_cell.csv
├── mesmer-exemplar-001_cell.csv
└── unmicst-exemplar-001_cell.csv
```

Mesmer configuration is specified here: https://github.com/labsyspharm/mcmicro/blob/4d0a38f944eb3a478ea6c5cb3122c8d8456a11a6/config/modules.config#L49-L56
I expect that future updates to Mesmer would generally only require incrementing the `version:` field.

Default parameters for Mesmer are specified here:
https://github.com/labsyspharm/mcmicro/blob/4d0a38f944eb3a478ea6c5cb3122c8d8456a11a6/config/modules.config#L125
(I should probably move `--output-name cell.tif` to be here instead of the above config.)
MCMICRO users can overwrite the defaults with `--mesmer-opts`. For example,

`nextflow run labsyspharm/mcmicro --in ./exemplar-001 --probability-maps mesmer --mesmer-opts '--image-mpp 0.25'`

P.S. Right now, it's a bit of a misnomer to specify `--probability-maps mesmer`, since Mesmer produces instance segmentation masks and not probability maps. We are discussing some possible new names for the different pipeline steps, so it's possible that future runs may use something like `--segmentation mesmer` instead.

**Comment by ngreenwald** [comment]
Great! I'm sure @oldridge will be excited to give it a try

**Comment by FloWuenne** [comment]
@ngreenwald 
While trying to run the mesmer implementation of MCMICRO, I encountered the following error, likely related to model download by Mesmer, that does not behave as expected when running via nextflow.

To reproduce try the following:
```
nextflow -profile singularity --in exemplar-001/ --probability-maps mesmer --start-at probability-maps
```

When I try to run this on the login node or submit via slurm on 2 separate, independent clusters, I get the following, similar error. This is however not related to space, as other processes and programs can write and my user account has a lot of space left on the cluster. Running mesmer directly via singularity (without nextflow) using the following command, downloads the model correctly into $HOME/.keras.

```
singularity exec vanvalenlab-deepcell-applications-0.3.0.img python /usr/src/app/run_app.py mesmer --squeeze --output-directory /output --output-name cell.tif --nuclear-image /input/exemplar-001.ome.tif
```

I have also brought this up directly in the MCMICRO repo, since I am not sure whether this is related to nextflow behaviour or explicit calls from the Mesmer container:

https://github.com/labsyspharm/mcmicro/pull/321

Thanks for helping with this! 

Error message: 

```
Caused by:
  Process `segmentation:worker (mesmer-1)` terminated with an error exit status (1)

Command executed:

  python /usr/src/app/run_app.py mesmer --squeeze --output-directory . --output-name cell.tif --nuclear-image exemplar-001.ome.tif

Command exit status:
  1

Command output:
  Downloading data from https://deepcell-data.s3-us-west-1.amazonaws.com/saved-models/MultiplexSegmentation-7.tar.gz
  14032896/96894291 [===>..........................] - ETA: 10s

Command error:
  2022-02-24 11:29:21.466174: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /.singularity.d/libs
  2022-02-24 11:29:21.466206: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
  /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
    "The `lr` argument is deprecated, use `learning_rate` instead.")
  Traceback (most recent call last):
    File "/usr/src/app/run_app.py", line 165, in <module>
      app = dca.utils.get_app(ARGS.app)
    File "/usr/src/app/deepcell_applications/utils.py", line 44, in get_app
      return app_map[name]['class'](**kwargs)
    File "/usr/local/lib/python3.6/dist-packages/deepcell/applications/mesmer.py", line 218, in __init__
      extract=True, cache_subdir='models'
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/data_utils.py", line 258, in get_file
      urlretrieve(origin, fpath, dl_progress)
    File "/usr/lib/python3.6/urllib/request.py", line 281, in urlretrieve
      tfp.write(block)
  OSError: [Errno 28] No space left on device
```

**Comment by j4fam** [comment]
Dear mesmer team @willgraf and @ngreenwald 

We are trying to run the mesmer module on a workstation behind a proxy and we are stuck with the following error message:

```
Error executing process > 'segmentation:worker (mesmer-1)'

Caused by:
  Process `segmentation:worker (mesmer-1)` terminated with an error exit status (1)

Command executed:

  python /usr/src/app/run_app.py mesmer --squeeze --output-directory . --output-name cell.tif --nuclear-image 220328_Tonsil_ABTest_2AB06_roi01_20x_small.tif

Command exit status:
  1

Command output:
  Downloading data from https://deepcell-data.s3-us-west-1.amazonaws.com/saved-models/MultiplexSegmentation-7.tar.gz

Command error:
      self.endheaders(body, encode_chunked=encode_chunked)
    File "/usr/lib/python3.6/http/client.py", line 1276, in endheaders
      self._send_output(message_body, encode_chunked=encode_chunked)
    File "/usr/lib/python3.6/http/client.py", line 1042, in _send_output
      self.send(msg)
    File "/usr/lib/python3.6/http/client.py", line 980, in send
      self.connect()
    File "/usr/lib/python3.6/http/client.py", line 1434, in connect
      super().connect()
    File "/usr/lib/python3.6/http/client.py", line 952, in connect
      (self.host,self.port), self.timeout, self.source_address)
    File "/usr/lib/python3.6/socket.py", line 724, in create_connection
      raise err
    File "/usr/lib/python3.6/socket.py", line 713, in create_connection
      sock.connect(sa)
  TimeoutError: [Errno 110] Connection timed out

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/data_utils.py", line 258, in get_file
      urlretrieve(origin, fpath, dl_progress)
    File "/usr/lib/python3.6/urllib/request.py", line 248, in urlretrieve
      with contextlib.closing(urlopen(url, data)) as fp:
    File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
      return opener.open(url, data, timeout)
    File "/usr/lib/python3.6/urllib/request.py", line 526, in open
      response = self._open(req, data)
    File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
      '_open', req)
    File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
      result = func(*args)
    File "/usr/lib/python3.6/urllib/request.py", line 1368, in https_open
      context=self._context, check_hostname=self._check_hostname)
    File "/usr/lib/python3.6/urllib/request.py", line 1327, in do_open
      raise URLError(err)
  urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/usr/src/app/run_app.py", line 165, in <module>
      app = dca.utils.get_app(ARGS.app)
    File "/usr/src/app/deepcell_applications/utils.py", line 44, in get_app
      return app_map[name]['class'](**kwargs)
    File "/usr/local/lib/python3.6/dist-packages/deepcell/applications/mesmer.py", line 218, in __init__
      extract=True, cache_subdir='models'
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/data_utils.py", line 262, in get_file
      raise Exception(error_msg.format(origin, e.errno, e.reason))
  Exception: URL fetch failure on https://deepcell-data.s3-us-west-1.amazonaws.com/saved-models/MultiplexSegmentation-7.tar.gz: None -- [Errno 110] Connection timed out
```

Is it possible to containerize this "MultiplexSegmentation-7.tar.gz" file or alternatively, provide a parameter to point to the path of this file that we save locally?
We can download the file manually, but cannot do this through the MCMICRO pipeline.

Thank you very much for your help!
~Johanna

**Comment by ngreenwald** [comment]
@msschwartz21, is it possible to create the image with the tar file already loaded into the application?

**Comment by msschwartz21** [comment]
@ngreenwald yes it should be possible. I would suggest creating a python script to download the models using the urls specified in the deepcell application files. That script could then be run as a step in the Dockerfile build. The risk of course is the size of the image getting unmanageable, but we can always reassess that if it becomes a problem.

**Comment by ArtemSokolov** [comment]
I just want to chime in here. @j4fam has originally posted to the MCMICRO repo, and it seems that she is getting two separate errors. 

@j4fam, correct me if I'm wrong but you are getting a timeout error when executing Mesmer inside the pipeline and a "no space left on disk" when executing Mesmer as a standalone container using Singularity.

I proposed exactly what you are suggestion, @willgraf: https://github.com/labsyspharm/mcmicro/pull/321#issuecomment-1168984333

My understanding is that Mesmer downloads files to `$HOME/.keras`. So, by mounting the directory with `-B`, Mesmer should theoretically have the ability to check if the model is already cached. However, @j4fam reports that she is able to manually download the model to `$HOME/.keras`, but doing so via `python /usr/src/app/run_app.py mesmer` triggers an "out of disk space" error. My only thought here is that Mesmer also writes to other directories, which are not mounted, but I don't know what those directories may be.

I am still not entirely sure what to do about the "timeout" error, but my hope was to get Mesmer working as a standalone container for @j4fam, before attempting to debug its interaction with the pipeline.

**Comment by ngreenwald** [comment]
So is this something specific to singularity @ArtemSokolov? We are able to run this container on its own without any memory issues

**Comment by ArtemSokolov** [comment]
Unfortunately, I have not been able to reproduce the issue on my local workstation. Singularity has no problem running the container if I mount `$HOME/.keras` to be accessible inside it. But the download seems to time out for @j4fam, and only when done through Mesmer (she reported that the manual `curl` works fine).

Is there a specific location in `$HOME/.keras` where the model has to exist to avoid Mesmer having to download it? One potential solution is to pre-download the model to that location, then mount `$HOME/.keras` for a Mesmer container.

**Comment by ngreenwald** [comment]
The logic for loading the weights file is here:
https://github.com/vanvalenlab/deepcell-tf/blob/master/deepcell/applications/mesmer.py#L213
If no weights file is found at the `archive_path`, the `tf.keras` function will attempt to download. 


If finding that path ends up being challenging (I haven't ever looked to see where it's saved before), the alternative is to change the behavior of the Mesmer application itself. 

You can see that the entire block for loading the weights is wrapped in an `if model is None` conditional. The user can provided a loaded model directly, which circumvents the need to download the weights. The current setup of this repo doesn't expose that kwarg to the user. However, if you wanted to mount the path to the model and then change a few lines to load in directly, that would need to be passed in the Mesmer application: https://github.com/vanvalenlab/deepcell-applications/blob/master/deepcell_applications/utils.py#L31
