### ISSUE TITLE
Encountered error  <COMPRESSION.LZW: 5> requires the 'imagecodecs' package

### ISSUE THREAD

**Issue by liuyang2006** [vanvalenlab/deepcell-applications#42]
Hi,

I run below command on v0.4.1, but encountered error:
```
python /usr/src/app/run_app.py mesmer --squeeze --output-directory . --output-name cell.tif --nuclear-image fv_uc_01_full.ome.tiff --nuclear-channel 0
```

Error message:
```
Traceback (most recent call last):
  File "/usr/src/app/run_app.py", line 60, in <module>
    run_application(dict(ARGS._get_kwargs()))
  File "/usr/src/app/deepcell_applications/app_runners.py", line 55, in run_application
    image = dca.prepare.prepare_input(arg_dict['app'], **arg_dict)
  File "/usr/src/app/deepcell_applications/prepare.py", line 36, in prepare_input
    return prepare_mesmer_input(**kwargs)
  File "/usr/src/app/deepcell_applications/prepare.py", line 60, in prepare_mesmer_input
    nuclear_img = dca.io.load_image(
  File "/usr/src/app/deepcell_applications/io.py", line 49, in load_image
    img = get_image(path)
  File "/usr/local/lib/python3.8/dist-packages/deepcell/utils/io_utils.py", line 50, in get_image
    return np.float32(imread(file_name))
  File "/usr/local/lib/python3.8/dist-packages/skimage/io/_io.py", line 53, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/usr/local/lib/python3.8/dist-packages/skimage/io/manage_plugins.py", line 207, in call_plugin
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/skimage/io/_plugins/tifffile_plugin.py", line 30, in imread
    return tifffile_imread(fname, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tifffile/tifffile.py", line 994, in imread
    return tif.asarray(
  File "/usr/local/lib/python3.8/dist-packages/tifffile/tifffile.py", line 3853, in asarray
    result = stack_pages(pages, out=out, maxworkers=maxworkers)
  File "/usr/local/lib/python3.8/dist-packages/tifffile/tifffile.py", line 18983, in stack_pages
    for _ in executor.map(func, pages, range(npages)):
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tifffile/tifffile.py", line 18974, in func
    page.asarray(lock=filecache.lock, out=out[index], **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tifffile/tifffile.py", line 7661, in asarray
    for _ in self.segments(
  File "/usr/local/lib/python3.8/dist-packages/tifffile/tifffile.py", line 7484, in segments
    yield decode(segment)
  File "/usr/local/lib/python3.8/dist-packages/tifffile/tifffile.py", line 7472, in decode
    return func(keyframe.decode(*args, **decodeargs))
  File "/usr/local/lib/python3.8/dist-packages/tifffile/tifffile.py", line 7020, in decode_raise_compression
    raise ValueError(f'{exc}')
ValueError: <COMPRESSION.LZW: 5> requires the 'imagecodecs' package

```

**Comment by rossbar** [comment]
This was fixed in version 0.4.1. If you are running in the container (as recommended) then all necessary dependencies should be present.

If you are somehow running outside of the container, then you will have to ensure everything is installed in your runtime environment yourself. `pip install -r requirements.txt` should do it. However; if you want to use mesmer directly without the containerization interface, it's strongly recommended that you use the `deepcell-tf` package directly.
